const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export { ADD_TO_CART, REMOVE_ITEM_FROM_CART, SAVE_SHIPPING_INFO };