const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"


const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
const MY_ORDER_FAIL = "MY_ORDER_FAIL";


const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";



const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";



const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";



const SINGLE_ORDER_DETAILS_REQUEST = "SINGLE_ORDER_DETAILS_REQUEST";
const SINGLE_ORDER_DETAILS_SUCCESS = "SINGLE_ORDER_DETAILS_SUCCESS";
const SINGLE_ORDER_DETAILS_FAIL = "SINGLE_ORDER_DETAILS_FAIL"


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    CREATE_ORDER_REQUEST,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_FAIL,
    MY_ORDER_REQUEST,
    MY_ORDER_SUCCESS,
    MY_ORDER_FAIL,
    ALL_ORDERS_REQUEST,
    ALL_ORDERS_SUCCESS,
    ALL_ORDERS_FAIL,
    UPDATE_ORDER_REQUEST,
    UPDATE_ORDER_SUCCESS,
    UPDATE_ORDER_FAIL,
    UPDATE_ORDER_RESET,
    DELETE_ORDER_REQUEST,
    DELETE_ORDER_SUCCESS,
    DELETE_ORDER_FAIL,
    DELETE_ORDER_RESET,
    SINGLE_ORDER_DETAILS_REQUEST,
    SINGLE_ORDER_DETAILS_SUCCESS,
    SINGLE_ORDER_DETAILS_FAIL,
    CLEAR_ERRORS
}
