const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"


const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
const MY_ORDER_FAIL = "MY_ORDER_FAIL"

const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    CREATE_ORDER_REQUEST,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_FAIL,
    MY_ORDER_REQUEST,
    MY_ORDER_SUCCESS,
    MY_ORDER_FAIL,
    CLEAR_ERRORS
}
