const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_SUCEESS = "ALL_PRODUCT_SUCEESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";



const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
const SINGLE_PRODUCT_SUCEESS = "SINGLE_PRODUCT_SUCEESS";
const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";



const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
    ALL_PRODUCT_REQUEST,
    ALL_PRODUCT_SUCEESS,
    ALL_PRODUCT_FAIL,
    SINGLE_PRODUCT_REQUEST,
    SINGLE_PRODUCT_SUCEESS,
    SINGLE_PRODUCT_FAIL,
    CLEAR_ERRORS
};