const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_SUCEESS = "ALL_PRODUCT_SUCEESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

const ADMIN_ALL_PRODUCT_REQUEST = "ADMIN_ALL_PRODUCT_REQUEST";
const ADMIN_ALL_PRODUCT_SUCEESS = "ADMIN_ALL_PRODUCT_SUCEESS";
const ADMIN_ALL_PRODUCT_FAIL = "ADMIN_ALL_PRODUCT_FAIL";


const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
const SINGLE_PRODUCT_SUCEESS = "SINGLE_PRODUCT_SUCEESS";
const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";


const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
const NEW_REVIEW_SUCEESS = "NEW_REVIEW_SUCEESS";
const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";


const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
    ALL_PRODUCT_REQUEST,
    ALL_PRODUCT_SUCEESS,
    ALL_PRODUCT_FAIL,
    ADMIN_ALL_PRODUCT_REQUEST,
    ADMIN_ALL_PRODUCT_SUCEESS,
    ADMIN_ALL_PRODUCT_FAIL,
    SINGLE_PRODUCT_REQUEST,
    SINGLE_PRODUCT_SUCEESS,
    SINGLE_PRODUCT_FAIL,
    NEW_REVIEW_REQUEST,
    NEW_REVIEW_SUCEESS,
    NEW_REVIEW_RESET,
    NEW_REVIEW_FAIL,
    CLEAR_ERRORS
};