const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCEESS = "LOGIN_SUCEESS";
const LOGIN_FAIL = "LOGIN_FAIL";


const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCEESS = "REGISTER_USER_SUCEESS";
const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";


const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
const LOAD_USER_SUCEESS = "LOAD_USER_SUCEESS";
const LOAD_USER_FAIL = "LOAD_USER_FAIL";


const LOGOUT_USER_SUCEESS = "LOGOUT_USER_SUCEESS";
const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";


const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
const UPDATE_PROFILE_SUCEESS = "UPDATE_PROFILE_SUCEESS";
const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";


const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
const UPDATE_PASSWORD_SUCEESS = "UPDATE_PASSWORD_SUCEESS";
const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";


const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
const GET_ALL_USER_SUCEESS = "GET_ALL_USER_SUCEESS";
const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";



const SINGLE_USER_DETAILS_REQUEST = "SINGLE_USER_DETAILS_REQUEST";
const SINGLE_USER_DETAILS_SUCEESS = "SINGLE_USER_DETAILS_SUCEESS";
const SINGLE_USER_DETAILS_FAIL = "SINGLE_USER_DETAILS_FAIL";


const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCEESS = "UPDATE_USER_SUCEESS";
const UPDATE_USER_RESET = "UPDATE_USER_RESET";
const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";



const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
const DELETE_USER_SUCEESS = "DELETE_USER_SUCEESS";
const DELETE_USER_RESET = "DELETE_USER_RESET";
const DELETE_USER_FAIL = "DELETE_USER_FAIL";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    LOGIN_REQUEST,
    LOGIN_SUCEESS,
    LOGIN_FAIL,
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCEESS,
    REGISTER_USER_FAIL,
    LOAD_USER_REQUEST,
    LOAD_USER_SUCEESS,
    LOAD_USER_FAIL,
    LOGOUT_USER_SUCEESS,
    LOGOUT_USER_FAIL,
    UPDATE_PROFILE_REQUEST,
    UPDATE_PROFILE_SUCEESS,
    UPDATE_PROFILE_RESET,
    UPDATE_PROFILE_FAIL,
    UPDATE_PASSWORD_REQUEST,
    UPDATE_PASSWORD_SUCEESS,
    UPDATE_PASSWORD_RESET,
    UPDATE_PASSWORD_FAIL,
    GET_ALL_USER_REQUEST,
    GET_ALL_USER_SUCEESS,
    GET_ALL_USER_FAIL,
    SINGLE_USER_DETAILS_REQUEST,
    SINGLE_USER_DETAILS_SUCEESS,
    SINGLE_USER_DETAILS_FAIL,
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCEESS,
    UPDATE_USER_RESET,
    UPDATE_USER_FAIL,
    DELETE_USER_REQUEST,
    DELETE_USER_SUCEESS,
    DELETE_USER_RESET,
    DELETE_USER_FAIL,
    CLEAR_ERRORS,
};