const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCEESS = "LOGIN_SUCEESS";
const LOGIN_FAIL = "LOGIN_FAIL";


const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCEESS = "REGISTER_USER_SUCEESS";
const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    LOGIN_REQUEST,
    LOGIN_SUCEESS,
    LOGIN_FAIL,
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCEESS,
    REGISTER_USER_FAIL,
    CLEAR_ERRORS,
};